### ISSUE TITLE
sap_hypervisor_node_preconfigure: Replacing multiple occurrence of openshift-cnv with a constant

### ISSUE THREAD

**Issue by geetikakay** [sap-linuxlab/community.sap_infrastructure#8]
Replacing multiple occurrence of  openshift-cnv  with a constant. Consider adding vars.yml
In case we need to make changes we just have one place to change. 

example:

```yaml
  tasks:
    - name: Ensure the OperatorGroup is present
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: operators.coreos.com/v1
          kind: OperatorGroup
          metadata:
            name: kubevirt-hyperconverged-group
            namespace: "{{ openshift_namespace }}"
          spec:
            targetNamespaces:
              - "{{ openshift_namespace }}"
```

Would like maintainers to think about this proposal so that i can proceed.
